### ISSUE TITLE
Base Layer not showing

### ISSUE THREAD

**Issue by hzrimtrog** [volaya/qgis-ol3#19]
Using the plugin, the 'update preview' button correctly shows my vector layer and base-layer selected.  However, when clicking 'preview in external browser' or 'export as open layers 3...', when I open the resulting file on my browser, it only shows my vector layer, not the base layer (even though base layer is checked).

This is happening is qgis 2.4.  In qgis 2.6 neither base nor vector layer is showing (in either preview or exported).

Windows 7 machine.

Let me know what else you need from me to help debug it.  And thanks for a wonderful plugin!

**Comment by lucacasagrande** [comment]
The problem with 2.6 should be fixed with a5edf35496ef071834fa19c08efd7bcd1f839862
