### ISSUE TITLE
Incorrect dictionary keys in QgsSimpleLineSymbolLayerV2

### ISSUE THREAD

**Issue by hoodlumbubo** [volaya/qgis-ol3#22]
https://github.com/volaya/qgis-ol3/blob/master/olwriter.py#L284-L286

In newer versions (don't know if it affects old version of QGIS), these need to change to:
* props["color"] -> props["line_color"]
* props["penstyle"] -> props["line_style"]
* props["width"]  ->  props["line_width"]

**Comment by lucacasagrande** [comment]
Thanks @hoodlumbubo, I'll fix the code.

**Comment by lucacasagrande** [comment]
Fixed in b289ed67cd4ca8689fa6151fce1e0353ad8ced91
