### ISSUE TITLE
Qgis crash trying to use plugin

### ISSUE THREAD

**Issue by marcobra** [volaya/qgis-ol3#24]
On Qgis 2.6.1-Brighton on ubuntu 14.04.1 64 bits i get qgis totally crash on all my try to use plugin, here some terminal messages to have some debug info.

Fatal: ASSERT failure in QVector<T>::operator[]: "index out of range", file /usr/include/qt4/QtCore/qvector.h, line 355
QGIS died on signal -1[New LWP 4279]
.....

in another try :

Traceback (most recent call last):
  File "/home/ubuntu/.qgis2/python/plugins/ol3/maindialog.py", line 93, in update
    writeOL(layers, groups, popup, visible, params, utils.tempFolder())
  File "/home/ubuntu/.qgis2/python/plugins/ol3/olwriter.py", line 32, in writeOL
    exportLayers(layers, folder, precision, optimize, usedFields)
  File "/home/ubuntu/.qgis2/python/plugins/ol3/utils.py", line 48, in exportLayers
    uri = TYPE_MAP[layer.wkbType()]
KeyError: 100

**Comment by lucacasagrande** [comment]
Thanks for the feedback @marcobra. Which layers (vector, wms, etc..) are opened in QGIS ?

**Comment by marcobra** [comment]
Tried on different vector shp file (epsg 3857) and openstreetmap as background coming from using Openlayers plugin.

**Comment by lucacasagrande** [comment]
There is no need to add layer for the background, you can choose it directly in the qgis-ol3 plugin. Can you try without the layer coming from OpenLayers plugin?

**Comment by lucacasagrande** [comment]
Please feel free to reopen it if needed.

**Comment by marcobra** [comment]
Yes tried without OpenLayers plugin, the issue is still present,  please do not close this issue...

**Comment by lucacasagrande** [comment]
Can you try with just this vector data?
https://dl.dropboxusercontent.com/u/348430/werk/ol3/test.zip

**Comment by marcobra** [comment]
With this dataset it works, i can see the osm background into preview, but not into external (working) browser, also in the generated page... i will send generated code to you via PM

**Comment by lucacasagrande** [comment]
Which Browser? Currently the background doesn't work in Firefox.

**Comment by marcobra** [comment]
yeah, Firefox

**Comment by lucacasagrande** [comment]
It will be fixed in the next release. It should be ready for the next week.

**Comment by pcav** [comment]
No crash here, with current versions

**Comment by lucacasagrande** [comment]
Feel free to reopen
