### ISSUE TITLE
Plugin Crashes Qgis

### ISSUE THREAD

**Issue by boesiii** [volaya/qgis-ol3#29]
I tried using your plugin and it caused Qgis to crash.  I was using two vector layers and a WMS layer.  Each vector layer had EPSG:2272 and the WMS layer had EPSG:4326.  I was using Qgis 2.4.  Please let me know if you need additional information.

**Comment by lucacasagrande** [comment]
Thank you for your feedback. Can you try removing the wms layer?

**Comment by boesiii** [comment]
I removed the WMS layer and Qgis still crashes

**Comment by boesiii** [comment]
When Qgis crashes there is a minidump file created.  Would you like me to upload it somehow?

**Comment by lucacasagrande** [comment]
Yes please. I don't have 2.4 installed, but I will compile one and I will try the plugin. Also, can you confirm that you are using the plugin's latest version?

**Comment by boesiii** [comment]
Luca,

 

Attached is the minidump file from Qgis.

 

Ed

**Comment by lucacasagrande** [comment]
@boesiii I can't see it.

**Comment by boesiii** [comment]
I don't see an option to upload a file.  I don't want to cut and paste because it over 39,000 lines of text.

**Comment by boesiii** [comment]
I am using version 0.22.  After looking at my data I think there is something "weird" with the projection of my data.  The data should have a projection of epsg:2272 but when I add the layer, Qgis does not recognize the projection and gives is a user projection of 100000.  

If I create a new layer inside Qgis with the projection of 2272 it does not crash.

**Comment by lucacasagrande** [comment]
If you go in the Properties Settings of the layer, you can set the SRS. Try set it to epsg:2272.

**Comment by lucacasagrande** [comment]
@boesiii I will close this as it seems related to data. Feel free to reopen if there are other problems.

**Comment by boesiii** [comment]
You were right, it something was wrong with my data.  After i cleaned it up it worked flawlessly.  Sorry for the noise.
