### ISSUE TITLE
Scalebar Overlaps OpenLayers Icon

### ISSUE THREAD

**Issue by boesiii** [volaya/qgis-ol3#30]
The scalebar overlaps the OpenLayers icon.  Could you move the scalebar over a tad.

![overlap](https://cloud.githubusercontent.com/assets/2079638/5923717/9a4cbb76-a623-11e4-9443-dc57d99ba722.PNG)

**Comment by lucacasagrande** [comment]
Fixed in e00017a462cdc5d23cc7883c78dc271cc296de7d
